name: Check CS

on:
    push:
    pull_request:
        types: [opened]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Check code style
        steps:
            -   uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
                with:
                    fetch-depth: 0

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: none
                    php-version: "8.1"
                    tools: cs2pr

            -   name: Install dependencies with composer
                run: composer install
                env:
                    COMPOSER_ROOT_VERSION: dev-master

            -   if: ${{ github.base_ref == '' }}
                run: composer cscheck

            -   name: Run diff-sniffer
                if: ${{ github.base_ref != '' }}
                run: composer cscheck -- --report=checkstyle | cs2pr
