name: Check CS

on:
    push:
    pull_request:
        types: [opened]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Check code style
        steps:
            -   uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
                with:
                    fetch-depth: 0

            -   name: Install PHP
                uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2
                with:
                    coverage: none
                    php-version: "8.1"
                    tools: cs2pr

            -   name: Install dependencies with composer
                run: composer install

            -   if: ${{ github.base_ref == '' }}
                run: composer cscheck

            -   name: Run diff-sniffer
                if: ${{ github.base_ref != '' }}
                run: composer cscheck -- --report=checkstyle | cs2pr
