name: PHPStan

on:
    push:
    pull_request:
        types: [opened]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Static analysis
        steps:
            -   uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
                with:
                    fetch-depth: 0

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: none
                    php-version: "8.3"
                    tools: cs2pr

            -   name: Install dependencies with composer
                run: composer install
                env:
                    COMPOSER_ROOT_VERSION: dev-master

            -   if: ${{ github.base_ref == '' }}
                run: composer phpstan

            -   name: Run a static analysis with phpstan/phpstan
                if: ${{ github.base_ref != '' }}
                run: composer phpstan -- --error-format=checkstyle | cs2pr
